# Generated by Django 3.1.4 on 2020-12-27 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTbAccess',
            fields=[
                ('access_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador de la llave de acceso')),
                ('access_key', models.TextField(blank=True, null=True, verbose_name='Llave de acceso')),
                ('access_description', models.TextField(blank=True, null=True, verbose_name='Descripción de la llave de acceso')),
            ],
            options={
                'verbose_name': 'Llave de acceso',
                'verbose_name_plural': 'Llaves de acceso',
                'db_table': 'api_tb_access',
            },
        ),
    ]
