# Generated by Django 3.1.4 on 2020-12-28 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('descarga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiTbUsersRfc',
            fields=[
                ('user_rfc_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Identificador')),
                ('user_rfc', models.TextField(blank=True, null=True, verbose_name='RFC')),
                ('user_rfc_clave', models.TextField(blank=True, null=True, verbose_name='Clave secreta')),
                ('user_rfc_location_cer', models.TextField(blank=True, null=True, verbose_name='URL del Certificado')),
                ('user_rfc_location_key', models.TextField(blank=True, null=True, verbose_name='URL de la llave')),
            ],
            options={
                'verbose_name': 'RFC de usuario',
                'verbose_name_plural': 'RFC de usuarios',
                'db_table': 'api_tb_users_rfc',
            },
        ),
    ]
